#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PATH=$PATH:$DIR/bin
export AIRFLOW_HOME=$DIR/airflow_home
export PYTHONPATH=$DIR/airflow_home
export AIRFLOW__CORE__DAGS_FOLDER=$DIR/airflow_home/dags
export AIRFLOW__CORE__BASE_LOG_FOLDER=$DIR/airflow_home/logs/tasks
export AIRFLOW__CORE__LOAD_EXAMPLES=False
#export AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql://airflow:airflow@127.0.0.1/airflow
export AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY=$DIR/airflow_home/logs/scheduler
export AIRFLOW__WEBSERVER__AUTHENTICATE=False
export AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080

exec airflow "$@"